# Task 1: 
 

##### 1. Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [7]:
def dividing(a,b):
    try:
        result=a//b
        print("The answer is:- ",result)
    except ZeroDivisionError:
        print("Number can not be divided by zero")
dividing(5,0)
        

Number can not be divided by zero


##### 2.Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

In [9]:
subjects=["Americans", "Indians"]
verbs=["Play", "watch"] 
objects=["Baseball","cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print("{} {} {}  ".format(i,j,k))

Americans Play Baseball  
Americans Play cricket  
Americans watch Baseball  
Americans watch cricket  
Indians Play Baseball  
Indians Play cricket  
Indians watch Baseball  
Indians watch cricket  


# Task 2: 

Que.1 Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 

In [28]:
import numpy as np
def alexfun(ser,inc=True):
    n=len(ser)
    list1=list()
    if inc==True:
        for i in range(0,n):
            for j in range(0,n):
                list1.append(ser[i]**j)
    else:
        for i in range(0,n):
            for j in range(n-1,-1,-1):
                list1.append(ser[i]**j)
    list1=np.asanyarray(list1)          
    arr=np.array([list1]).reshape(n,n)
    return arr
ser=list(map(int,input("Enter the series:- ").split()))
result=alexfun(ser)
print(result)
newresult=alexfun(ser,False)
print("-"*40)
print(newresult)

Enter the series:- 2 3 4 5
[[  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
----------------------------------------
[[  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
